server.port = 8085
spring.application.name=consumer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ari
spring.rabbitmq.password=12345

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fachrianata1999@gmail.com
spring.mail.password=qoyrvaogauiumszl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true